CREATE TABLE IF NOT EXISTS Fruits (
    -- _id INTEGER PRIMARY KEY AUTOINCREMENT,
    fruit TEXT NOT NULL,
    vitamin TEXT NOT NULL,
    value NUMBER NOT NULL,
    PRIMARY KEY (fruit, vitamin)
);

INSERT INTO Fruits VALUES('Apricots', 'Vitamin A', 0.2);
INSERT INTO Fruits VALUES('Apricots', 'Vitamin B1', 0.06);
INSERT INTO Fruits VALUES('Apricots', 'Vitamin B2', 0.05);
INSERT INTO Fruits VALUES('Apricots', 'Vitamin B6', 0.06);
INSERT INTO Fruits VALUES('Apricots', 'Vitamin C', 5000);
INSERT INTO Fruits VALUES('Apricots', 'Folate (folic acid)', 0.004);
INSERT INTO Fruits VALUES('Apple', 'Vitamin A', 0.005);
INSERT INTO Fruits VALUES('Apple', 'Vitamin B1', 0.02);
INSERT INTO Fruits VALUES('Apple', 'Vitamin B2', 0.01);
INSERT INTO Fruits VALUES('Apple', 'Vitamin B6', 0.05);
INSERT INTO Fruits VALUES('Apple', 'Vitamin C', 5000);
INSERT INTO Fruits VALUES('Apple', 'Folate (folic acid)', 0.003);
INSERT INTO Fruits VALUES('Banana', 'Vitamin A', 0.008);
INSERT INTO Fruits VALUES('Banana', 'Vitamin B1', 0.04);
INSERT INTO Fruits VALUES('Banana', 'Vitamin B2', 0.03);
INSERT INTO Fruits VALUES('Banana', 'Vitamin B6', 0.36);
INSERT INTO Fruits VALUES('Banana', 'Vitamin C', 10000);
INSERT INTO Fruits VALUES('Banana', 'Folate (folic acid)', 0.016);
INSERT INTO Fruits VALUES('Blackberries', 'Vitamin A', 0.015);
INSERT INTO Fruits VALUES('Blackberries', 'Vitamin B1', 0.08);
INSERT INTO Fruits VALUES('Blackberries', 'Vitamin B2', 0.04);
INSERT INTO Fruits VALUES('Blackberries', 'Vitamin B6', 0.07);
INSERT INTO Fruits VALUES('Blackberries', 'Vitamin C', 150000);
INSERT INTO Fruits VALUES('Blackberries', 'Folate (folic acid)', 0.008);
INSERT INTO Fruits VALUES('Cherries', 'Vitamin A', 0.012);
INSERT INTO Fruits VALUES('Cherries', 'Vitamin B1', 0.02);
INSERT INTO Fruits VALUES('Cherries', 'Vitamin B2', 0.02);
INSERT INTO Fruits VALUES('Cherries', 'Vitamin B6', 0.04);
INSERT INTO Fruits VALUES('Cherries', 'Vitamin C', 10000);
INSERT INTO Fruits VALUES('Cherries', 'Folate (folic acid)', 0.004);
INSERT INTO Fruits VALUES('Grapefruit', 'Vitamin A', 0.028);
INSERT INTO Fruits VALUES('Grapefruit', 'Vitamin B1', 0.07);
INSERT INTO Fruits VALUES('Grapefruit', 'Vitamin B2', 0.02);
INSERT INTO Fruits VALUES('Grapefruit', 'Vitamin B6', 0.03);
INSERT INTO Fruits VALUES('Grapefruit', 'Vitamin C', 40000);
INSERT INTO Fruits VALUES('Grapefruit', 'Folate (folic acid)', 0.015);
INSERT INTO Fruits VALUES('Grapes', 'Vitamin A', 0.005);
INSERT INTO Fruits VALUES('Grapes', 'Vitamin B1', 0.03);
INSERT INTO Fruits VALUES('Grapes', 'Vitamin B2', 0.01);
INSERT INTO Fruits VALUES('Grapes', 'Vitamin B6', 0.08);
INSERT INTO Fruits VALUES('Grapes', 'Vitamin C', 3000);
INSERT INTO Fruits VALUES('Grapes', 'Folate (folic acid)', 0.001);
INSERT INTO Fruits VALUES('Kiwi', 'Vitamin A', 0.007);
INSERT INTO Fruits VALUES('Kiwi', 'Vitamin B1', 0.01);
INSERT INTO Fruits VALUES('Kiwi', 'Vitamin B2', 0.02);
INSERT INTO Fruits VALUES('Kiwi', 'Vitamin B6', 0.12);
INSERT INTO Fruits VALUES('Kiwi', 'Vitamin C', 70000);
INSERT INTO Fruits VALUES('Kiwi', 'Folate (folic acid)', 0.023);
INSERT INTO Fruits VALUES('Lemon', 'Vitamin A', 0.001);
INSERT INTO Fruits VALUES('Lemon', 'Vitamin B1', 0.06);
INSERT INTO Fruits VALUES('Lemon', 'Vitamin B2', 0.02 );
INSERT INTO Fruits VALUES('Lemon', 'Vitamin B6', 0.04);
INSERT INTO Fruits VALUES('Lemon', 'Vitamin C', 40000);
INSERT INTO Fruits VALUES('Lemon', 'Folate (folic acid)', 0.008);
INSERT INTO Fruits VALUES('Lime', 'Vitamin A', 0.03);
INSERT INTO Fruits VALUES('Lime', 'Vitamin B1', 0.43);
INSERT INTO Fruits VALUES('Lime', 'Vitamin B2', 0.020);
INSERT INTO Fruits VALUES('Lime', 'Vitamin B6', 29.1);
INSERT INTO Fruits VALUES('Lychee', 'Vitamin A', 0.002);
INSERT INTO Fruits VALUES('Lychee', 'Vitamin B1', 0.09);
INSERT INTO Fruits VALUES('Lychee', 'Vitamin B2', 0.04);
INSERT INTO Fruits VALUES('Lychee', 'Vitamin B6', 0.04);
INSERT INTO Fruits VALUES('Lychee', 'Vitamin C', 23000);
INSERT INTO Fruits VALUES('Mango', 'Vitamin A', 0.053);
INSERT INTO Fruits VALUES('Mango', 'Vitamin B1', 0.03);
INSERT INTO Fruits VALUES('Mango', 'Vitamin B2', 0.04);
INSERT INTO Fruits VALUES('Mango', 'Vitamin B6', 0.04);
INSERT INTO Fruits VALUES('Mango', 'Vitamin C', 23000);
INSERT INTO Fruits VALUES('Mango', 'Folate (folic acid)', 0.023);
INSERT INTO Fruits VALUES('Orange', 'Vitamin A', 0.012);
INSERT INTO Fruits VALUES('Orange', 'Vitamin B1', 0.07);
INSERT INTO Fruits VALUES('Orange', 'Vitamin B2', 0.03);
INSERT INTO Fruits VALUES('Orange', 'Vitamin B6', 0.06);
INSERT INTO Fruits VALUES('Orange', 'Vitamin C', 49000);
INSERT INTO Fruits VALUES('Orange', 'Folate (folic acid)', 0.018);
INSERT INTO Fruits VALUES('Peach', 'Vitamin A', 0.016);
INSERT INTO Fruits VALUES('Peach', 'Vitamin B1', 0.01);
INSERT INTO Fruits VALUES('Peach', 'Vitamin B2', 0.02);
INSERT INTO Fruits VALUES('Peach', 'Vitamin B6', 0.02);
INSERT INTO Fruits VALUES('Peach', 'Vitamin C', 7000);
INSERT INTO Fruits VALUES('Peach', 'Folate (folic acid)', 0.002);
INSERT INTO Fruits VALUES('Pear', 'Vitamin A', 0.002);
INSERT INTO Fruits VALUES('Pear', 'Vitamin B1', 0.01);
INSERT INTO Fruits VALUES('Pear', 'Vitamin B2', 0.01);
INSERT INTO Fruits VALUES('Pear', 'Vitamin B6', 0.02);
INSERT INTO Fruits VALUES('Pear', 'Vitamin C', 4000);
INSERT INTO Fruits VALUES('Pear', 'Folate (folic acid)', 0.001);
INSERT INTO Fruits VALUES('Pineapple', 'Vitamin B1', 0.07);
INSERT INTO Fruits VALUES('Pineapple', 'Vitamin B2', 0.02);
INSERT INTO Fruits VALUES('Pineapple', 'Vitamin B6', 0.09);
INSERT INTO Fruits VALUES('Pineapple', 'Vitamin C', 25000);
INSERT INTO Fruits VALUES('Pineapple', 'Folate (folic acid)', 0.004);
INSERT INTO Fruits VALUES('Plum', 'Vitamin A', 0.062);
INSERT INTO Fruits VALUES('Plum', 'Vitamin B1', 0.02);
INSERT INTO Fruits VALUES('Plum', 'Vitamin B2', 0.03);
INSERT INTO Fruits VALUES('Plum', 'Vitamin B6', 0.1);
INSERT INTO Fruits VALUES('Plum', 'Vitamin C', 5000);
INSERT INTO Fruits VALUES('Plum', 'Folate (folic acid)', 0.002);
INSERT INTO Fruits VALUES('Pumpkin', 'Vitamin A', 0.025);
INSERT INTO Fruits VALUES('Pumpkin', 'Vitamin B1', 0.04);
INSERT INTO Fruits VALUES('Pumpkin', 'Vitamin B2', 0.04);
INSERT INTO Fruits VALUES('Pumpkin', 'Vitamin B6', 0.02);
INSERT INTO Fruits VALUES('Pumpkin', 'Vitamin C', 16000);
INSERT INTO Fruits VALUES('Pumpkin', 'Folate (folic acid)', 0.007);
INSERT INTO Fruits VALUES('Raspberries', 'Vitamin A', 0.004);
INSERT INTO Fruits VALUES('Raspberries', 'Vitamin B1', 0.09);
INSERT INTO Fruits VALUES('Raspberries', 'Vitamin B2', 0.06);
INSERT INTO Fruits VALUES('Raspberries', 'Vitamin B6', 0.06);
INSERT INTO Fruits VALUES('Raspberries', 'Vitamin C', 5000);
INSERT INTO Fruits VALUES('Raspberries', 'Folate (folic acid)', 0.024);
INSERT INTO Fruits VALUES('Strawberry', 'Vitamin A', 0.002);
INSERT INTO Fruits VALUES('Strawberry', 'Vitamin B1', 0.02);
INSERT INTO Fruits VALUES('Strawberry', 'Vitamin B2', 0.03);
INSERT INTO Fruits VALUES('Strawberry', 'Vitamin B6', 0.06);
INSERT INTO Fruits VALUES('Strawberry', 'Vitamin C', 60000);
INSERT INTO Fruits VALUES('Strawberry', 'Folate (folic acid)', 0.065);
INSERT INTO Fruits VALUES('Tomato', 'Vitamin A', 0.088);
INSERT INTO Fruits VALUES('Tomato', 'Vitamin B1', 0.05);
INSERT INTO Fruits VALUES('Tomato', 'Vitamin B2', 0.02);
INSERT INTO Fruits VALUES('Tomato', 'Vitamin B6', 0.08);
INSERT INTO Fruits VALUES('Tomato', 'Vitamin C', 15000);
INSERT INTO Fruits VALUES('Tomato', 'Folate (folic acid)', 0.008);
INSERT INTO Fruits VALUES('Water melon', 'Vitamin A', 0.045);
INSERT INTO Fruits VALUES('Water melon', 'Vitamin B1', 0.04);
INSERT INTO Fruits VALUES('Water melon', 'Vitamin B2', 0.05);
INSERT INTO Fruits VALUES('Water melon', 'Vitamin B6', 0.07);
INSERT INTO Fruits VALUES('Water melon', 'Vitamin C', 6000);
INSERT INTO Fruits VALUES('Water melon', 'Folate (folic acid)', 0.001);